### ISSUE TITLE
Installation issues with Python 3.11 & conda

### ISSUE THREAD

**Issue by do-me** [wilsonjr/humap#11]
Couldn't install humap with Python 3.11 and conda. If I understand the readme correctly it's supposed to work without having to manually install anything else before right? Or do I still need to manually download eigen before running the command?

None of these work:
`conda install humap`
`conda install conda-forge::humap`

```
Retrieving notices: ...working... done
Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - humap

Current channels:

  - defaults
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org/

and use the search bar at the top of the page.
```

What versions are actually compatible? Or is there something I should consider when installing on MacOS?

**Comment by wilsonjr** [comment]
Hello, @do-me! Yeah, I still don't support arm64 machines. For that, I recommend following the *manual installation* steps -- I'm also going to try from my side.

Please let me know if you succeed or if you have any issues.

**Comment by do-me** [comment]
I didn't succeed. I Installed all deps in virtual env, then added the Eigen dir in `/usr/local/include/Eigen` and tried to run `pip install humap`. Also tried `brew install eigen` which installs eigen3 under `opt/homebrew/include/eigen3/Eigen` and then exporting the path.

Result: 

```
(py3.11) ➜  ~ pip install humap
Collecting humap
  Using cached humap-0.2.8.tar.gz (24.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: humap
  Building wheel for humap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for humap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Compiling for MacOS
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.1-arm64-cpython-311/humap
      copying humap/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/humap
      copying humap/humap.py -> build/lib.macosx-11.1-arm64-cpython-311/humap
      running build_ext
      clang++ -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -I/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include/python3.11 -c flagcheck.cpp -o flagcheck.o -std=c++17
      building '_hierarchical_umap' extension
      creating build/temp.macosx-11.1-arm64-cpython-311/src/cpp/external/efanna
      clang++ -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -DVERSION_INFO=0.2.8 -I/private/var/folders/rw/g3mzqszj4wq9d6qwvc0dlrym0000gn/T/pip-build-env-1vrp4k3u/overlay/lib/python3.11/site-packages/pybind11/include -I/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include/python3.11 -c src/cpp/external/efanna/index.cpp -o build/temp.macosx-11.1-arm64-cpython-311/src/cpp/external/efanna/index.o -std=c++17 -mmacosx-version-min=10.14 -fvisibility=hidden -g0 -O3 -std=c++11 -fPIC -fopenmp -DINFO -I/usr/local/include
      clang++: error: unsupported option '-fopenmp'
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for humap
Failed to build humap
ERROR: Could not build wheels for humap, which is required to install pyproject.toml-based projects
```

**Comment by wilsonjr** [comment]
I could get it installed with:

1. Install `libomp`:

`brew install libomp`

and it will output something like:

```
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
```

2. Update `darwin` install. The `LDFLAGS` goes in `extra_link_args` and `CPPFLAGS` goes in `extra_compile_args` (assuming that you have `XCode`, add '-Xclang' before '-fopenmp' too):

```
extra_compile_args = ['-O3', '-std=c++11', '-fPIC',  '-DINFO', '-Xclang', '-fopenmp', '-I/opt/homebrew/opt/libomp/include', '-I/usr/local/include'],
extra_link_args = ['-O3', '-std=c++11', '-fPIC', '-DINFO', '-Xclang', '-fopenmp', '-L/opt/homebrew/opt/libomp/lib', '-I/usr/local/include'],
```

3. Compile with and install:

```
python setup.py bdist_wheel 
pip install dist/[NAME OF THE .whl]
```

Let me know if it helps!

**Comment by do-me** [comment]
Thanks for your guidance. I followed all the steps and managed to build a wheel and install it, but importing humap still doesn't work: 

```bash
(py3.11) ➜  humap git:(master) ✗ pip uninstall humap
Found existing installation: humap 0.2.9
Uninstalling humap-0.2.9:
  Would remove:
    /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/_hierarchical_umap.cpython-311-darwin.so
    /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/humap-0.2.9.dist-info/*
    /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/humap/*
Proceed (Y/n)? Y
  Successfully uninstalled humap-0.2.9
(py3.11) ➜  humap git:(master) ✗ pip install dist/humap-0.2.9-cp311-cp311-macosx_11_0_arm64.whl
Processing ./dist/humap-0.2.9-cp311-cp311-macosx_11_0_arm64.whl
Installing collected packages: humap
Successfully installed humap-0.2.9
(py3.11) ➜  humap git:(master) ✗ python minimal_test.py                                        
Traceback (most recent call last):
  File "/Users/dome/work/general/humap/minimal_test.py", line 1, in <module>
    import humap 
    ^^^^^^^^^^^^
  File "/Users/dome/work/general/humap/humap/__init__.py", line 1, in <module>
    from .humap import HUMAP
  File "/Users/dome/work/general/humap/humap/humap.py", line 5, in <module>
    import _hierarchical_umap
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/_hierarchical_umap.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_barrier'
(py3.11) ➜  humap git:(master) ✗ 
```

**Comment by wilsonjr** [comment]
Yeah, I'm still trying to figure out why such an issue occurs in terminal but not in jupyter-lab.

**Comment by do-me** [comment]
So running the same commands from within an ipykernel in a virtual env & with os.env vars works? :D 
Would you mind sharing that notebook too?

**Comment by wilsonjr** [comment]
> So running the same commands from within an ipykernel in a virtual env & with os.env vars works? :D Would you mind sharing that notebook too?

Sorry, I meant that I don't get the same error after installation if I try to import `humap` within ipykernel. But this seems like an incompatible version of libomp (LLVM) or libiomp (Intel OneAPI) -- will take a look again.

**Comment by wilsonjr** [comment]
Please add `-lomp` in `extra_link_args`:

```
extra_compile_args = ['-O3', '-std=c++11', '-fPIC',  '-DINFO', '-Xclang', '-fopenmp', '-I/opt/homebrew/opt/libomp/include', '-I/usr/local/include'],
extra_link_args = ['-O3', '-std=c++11', '-fPIC', '-DINFO','-Xclang', '-fopenmp', '-L/opt/homebrew/opt/libomp/lib', '-I/usr/local/include', '-lomp'],
```

It should work now.

**Comment by do-me** [comment]
Unfortunately not:

```bash
(py3.11) ➜  humap git:(master) ✗ eval $(brew info libomp | grep -E "(CPPFLAGS|LDFLAGS)"); python setup.py bdist_wheel           

Compiling for MacOS
running bdist_wheel
running build
running build_py
copying humap/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/humap
copying humap/humap.py -> build/lib.macosx-11.1-arm64-cpython-311/humap
running build_ext
clang++ -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include -arch arm64 -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/include/python3.11 -c flagcheck.cpp -o flagcheck.o -std=c++17
/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.macosx-11.1-arm64/wheel
running install
running install_lib
creating build/bdist.macosx-11.1-arm64/wheel
creating build/bdist.macosx-11.1-arm64/wheel/humap
copying build/lib.macosx-11.1-arm64-cpython-311/humap/__init__.py -> build/bdist.macosx-11.1-arm64/wheel/./humap
copying build/lib.macosx-11.1-arm64-cpython-311/humap/humap.py -> build/bdist.macosx-11.1-arm64/wheel/./humap
copying build/lib.macosx-11.1-arm64-cpython-311/_hierarchical_umap.cpython-311-darwin.so -> build/bdist.macosx-11.1-arm64/wheel/.
running install_egg_info
running egg_info
writing humap.egg-info/PKG-INFO
writing dependency_links to humap.egg-info/dependency_links.txt
writing requirements to humap.egg-info/requires.txt
writing top-level names to humap.egg-info/top_level.txt
reading manifest file 'humap.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'humap.egg-info/SOURCES.txt'
Copying humap.egg-info to build/bdist.macosx-11.1-arm64/wheel/./humap-0.2.9-py3.11.egg-info
running install_scripts
creating build/bdist.macosx-11.1-arm64/wheel/humap-0.2.9.dist-info/WHEEL
creating 'dist/humap-0.2.9-cp311-cp311-macosx_11_0_arm64.whl' and adding 'build/bdist.macosx-11.1-arm64/wheel' to it
adding '_hierarchical_umap.cpython-311-darwin.so'
adding 'humap/__init__.py'
adding 'humap/humap.py'
adding 'humap-0.2.9.dist-info/LICENSE'
adding 'humap-0.2.9.dist-info/METADATA'
adding 'humap-0.2.9.dist-info/WHEEL'
adding 'humap-0.2.9.dist-info/top_level.txt'
adding 'humap-0.2.9.dist-info/RECORD'
removing build/bdist.macosx-11.1-arm64/wheel

(py3.11) ➜  humap git:(master) ✗ pip install dist/humap-0.2.9-cp311-cp311-macosx_11_0_arm64.whl 
Processing ./dist/humap-0.2.9-cp311-cp311-macosx_11_0_arm64.whl
Installing collected packages: humap
Successfully installed humap-0.2.9

(py3.11) ➜  humap git:(master) ✗ python minimal_test.py                                        
Traceback (most recent call last):
  File "/Users/dome/work/general/humap/minimal_test.py", line 1, in <module>
    import humap 
    ^^^^^^^^^^^^
  File "/Users/dome/work/general/humap/humap/__init__.py", line 1, in <module>
    from .humap import HUMAP
  File "/Users/dome/work/general/humap/humap/humap.py", line 5, in <module>
    import _hierarchical_umap
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/_hierarchical_umap.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_barrier'
(py3.11) ➜  humap git:(master) ✗ 
```

**Comment by wilsonjr** [comment]
Hmm it seems that you didn't build again? Can you delete `build/` and `dist/` folders and try again? Alternatively, run `python setup.py clean --all` 

You have the compile all cpp files again

**Comment by do-me** [comment]
That was it, thanks :) 
Now I can finally go play with it!

```
(py3.11) ➜  humap git:(master) ✗ python minimal_test.py                                                              
imported :)
```
